export const cards = [
  {
    name: "Microwave",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "microwave_gen",
  },
  {
    name: "Oven",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "oven_gen",
  },
  {
    name: "Diswasher",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "dishwasher_gen",
  },
  {
    name: "Fridge",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "kitchen",
  },
  {
    name: "Kettle",
    room: "kitchen",
    tags: ["Object"],
    icon: "kettle",
  },
  {
    name: "Blender",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "blender",
  },
  {
    name: "Sink",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "faucet",
  },
  {
    name: "Range hood",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "range_hood",
  },
  {
    name: "Eggs",
    room: "kitchen",
    tags: ["Dairy"],
    icon: "egg_alt",
  },
  {
    name: "Ice cream",
    room: "kitchen",
    tags: ["Dessert"],
    icon: "icecream",
  },
  {
    name: "Cake",
    room: "kitchen",
    tags: ["Dessert"],
    icon: "cake",
  },
  {
    name: "Wine",
    room: "kitchen",
    tags: ["Beverages"],
    icon: "liquor",
  },
  {
    name: "Spoons",
    room: "kitchen",
    tags: ["Cutlery"],
    icon: "flatware",
  },
  {
    name: "Forks",
    room: "kitchen",
    tags: ["Cutlery"],
    icon: "flatware",
  },
  {
    name: "Knife",
    room: "kitchen",
    tags: ["Cutlery"],
    icon: "flatware",
  },
  {
    name: "Gas tank",
    room: "kitchen",
    tags: ["Other"],
    icon: "propane_tank",
  },
  {
    name: "Coffee maker",
    room: "kitchen",
    tags: ["Appliances"],
    icon: "coffee_maker",
  },
  {
    name: "Soap",
    room: "kitchen",
    tags: ["Cleaning"],
    icon: "soap",
  },

  {
    name: "Soap",
    room: "bathroom",
    tags: ["Cleaning"],
    icon: "soap",
  },
  {
    name: "Air freshener",
    room: "bathroom",
    tags: ["Cleaning"],
    icon: "air_freshener",
  },

  {
    name: "Closet hangers",
    room: "bedroom",
    tags: ["Other"],
    icon: "styler",
  },
  {
    name: "Bed",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "king_bed",
  },
  {
    name: "Lamp",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "light",
  },
  {
    name: "Iron",
    room: "bedroom",
    tags: ["Appliances"],
    icon: "iron",
  },
  {
    name: "Desk",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "desk",
  },
  {
    name: "Dresser",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "dresser",
  },
  {
    name: "Stroller",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "stroller",
  },
  {
    name: "Blanket",
    room: "bedroom",
    tags: ["Furniture"],
    icon: "blanket",
  },

  {
    name: "Fire extinguisher",
    room: "garage",
    tags: [],
    icon: "fire_extinguisher",
  },
];
