export interface Meal {
  readonly idMeal: string;
  strMeal: string;
  strDrinkAlternate?: string | number;
  strCategory: string;
  strArea: string;
  strInstructions: string;
  strMealThumb: string;
  strTags: string;
  strYoutube: string;
  strIngredient1?: string;
  strIngredient2?: string;
  strIngredient3?: string;
  strIngredient4?: string;
  strIngredient5?: string;
  strIngredient6?: string;
  strIngredient7?: string;
  strIngredient8?: string;
  strIngredient9?: string;
  strIngredient10?: string;
  strIngredient11?: string;
  strIngredient12?: string;
  strIngredient13?: string;
  strIngredient14?: string;
  strIngredient15?: string;
  strIngredient16?: string | number;
  strIngredient17?: string | number;
  strIngredient18?: string | number;
  strIngredient19?: string | number;
  strIngredient20?: string | number;
  strMeasure1?: string;
  strMeasure2?: string;
  strMeasure3?: string;
  strMeasure4?: string;
  strMeasure5?: string;
  strMeasure6?: string;
  strMeasure7?: string;
  strMeasure8?: string;
  strMeasure9?: string;
  strMeasure10?: string;
  strMeasure11?: string;
  strMeasure12?: string;
  strMeasure13?: string;
  strMeasure14?: string;
  strMeasure15?: string;
  strMeasure16?: string | number;
  strMeasure17?: string | number;
  strMeasure18?: string | number;
  strMeasure19?: string | number;
  strMeasure20?: string | number;
  strSource: string | number;
  strImageSource: string | number;
  strCreativeCommonsConfirmed: string | number;
  dateModified: string | number;
}
