export const AutocompleteData = [
  "Bathroom Sink",
  "Shower",
  "Shower Curtain",
  "Towel Rack",
  "Hand Towels",
  "Bath Towels",
  "Face Cloth",
  "Bath Tub",
  "Soap Dish",
  "Air Freshener",
  "Bathroom Mat",
  "Plunger",
  "Toilet Brush",
  "Waste Basket",
  "Toilet Cleaning Supplies",
  "Toilet Roll with Holder",
  "Kitchen Table",
  "Gas Cylinder",
  "Gas Stove",
  "Microwave Oven",
  "Gas Oven",
  "Induction Cooktop",
  "Mixer & Grinder",
  "Hand Blender",
  "Juicer",
  "Bread Pin",
  "Electric Toaster",
  "Electric Kettle",
  "Coffee Maker",
  "Dustbin",
  "Paper Towel Holder",
  "Exhaust Fan or Kitchen Chimney",
  "Chef’s Knife",
  "Cutting Board",
  "Can",
  "Bottle Opener",
  "Measuring Cups",
  "Measuring Spoons",
  "Mixing Bowls",
  "Ladle",
  "Spatula",
  "Colander",
  "Vegetable Peeler",
  "Potato Masher",
  "Whisk",
  "Grater",
  "Fry Pan",
  "Sauté Pan",
  "Kadahi",
  "Saucepan",
  "Small Pots",
  "Large Pots",
  "Pressure Cooker",
  "Baking Tray",
  "Jug",
  "Mugs",
  "Cups",
  "Condiment holders",
  "Stockpot",
  "Slotted Spoon",
  "Tongs",
  "Oven Mitts",
  "Food Storage Containers",
  "Aluminum Foil",
  "Heavy Sponges",
  "Dish Rack",
  "Ice Cube Tray",
  "Small Trash Bags",
  "Large Trash Bags",
  "Kitchen Sponge",
  "Kitchen Scrubber",
  "Wiping Clothes",
  "Kitchen Towels",
  "Washing Detergent",
  "General Disinfectant",
  "Cleaning Sprays",
  "Mop",
  "Bucket",
  "Dustpan",
  "Vacuum Cleaner",
  "Bed",
  "Bedside Table ",
  "Lamp",
  "Bed End Bench",
  "Couch",
  "Chest of Drawer",
  "Wardrobe",
  "Clock",
  "Mattress",
  "Pillows",
  "Dresser",
  "Bedsheets",
  "Side Tables",
  "Bathroom Sink",
  "Shower",
  "Shower Curtain",
  "Towel Rack",
  "Hand Towels",
  "Bath Towels",
  "Face Cloth",
  "Bath Tub",
  "Soap Dish",
  "Air Freshener",
  "Bathroom Mat",
  "Plunger",
  "Toilet Brush",
  "Waste Basket",
  "Toilet Cleaning Supplies",
  "Toilet Roll",
  "Sofa & Sofa Set",
  "Couch",
  "Coffee Table",
  "Bookshelves",
  "TV",
  "Speaker",
  "Paintings",
  "Photo frames",
  "Sofa throws",
  "Cabinets",
  "Armchairs",
  "Rocking Chair",
  "Flashlight",
  "Smoke Alarm",
  "Fire Extinguisher",
  "Fire Blanket",
  "First Aid Box",
  "Extra Batteries",
  "Knife",
  "Drill Machine",
  "Measuring Tape",
  "Heavy Duty Packaging Tape",
  "Step Ladder",
  "Screws & Screwdrivers",
  "Electricity Taster",
  "Wire Cutter",
  "Hammer",
  "Spare Light Bulbs",
  "Batteries",
  "Wrenches",
  "Laundry Basket",
  "Laundry Tub",
  "Washing Machine",
  "Iron",
  "Ironing Board",
  "Clothes Horse"
];
