import ForwardedEmail from "@/emails/forwarded";
import { getApiParams } from "@/lib/getApiParams";
import { handleApiError } from "@/lib/handleApiError";
import { Notification } from "@/lib/notifications";
import { prisma } from "@/lib/prisma";
import { generateRandomString } from "@/lib/randomString";
import { render } from "@react-email/components";
import markdown from "@wcj/markdown-to-html";
import dayjs from "dayjs";
import tz from "dayjs/plugin/timezone";
import utc from "dayjs/plugin/utc";
import { NextRequest } from "next/server";
export const dynamic = "force-dynamic";

dayjs.extend(utc);
dayjs.extend(tz);

const getDescription = async (content): Promise<string> => {
  try {
    const res = await fetch(
      "https://router.huggingface.co/v1/chat/completions",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${process.env.IMAGE_CAPTIONING_TOKEN}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          model: "deepseek-ai/DeepSeek-V3.1:fireworks-ai",
          messages: [
            {
              role: "system",
              content: `You are an AI which will summarize a user's email in 2-5 bullet points. You will not include any surrounding text. Format using markdown. You will address the user in first person, as if they're reading this description in their to-do list. Each bullet point must start with a non-repeating emoji in plain text (example: 🔥).`,
            },
            {
              role: "user",
              content: `<!DOCTYPE html><html><body><p>Hi Alex,</p><p>Just a reminder that we have our project sync scheduled for <b>Wednesday at 3:00 PM</b> in the main conference room.<br>We’ll go over:<br>- Current progress updates<br>- Roadblocks or challenges<br>- Next week’s goals</p><p>Please bring your notes and any updates you’d like to share.</p><p>Best,<br>Manu</p></body></html>`,
            },
            {
              role: "system",
              content: `* 📅 Reminder: Project sync on Wednesday at 3:00 PM in main conference room
* ✅ Bring updates on progress, roadblocks, and next week’s goals
* 📝 Prepare notes to share during the meeting`,
            },
            {
              role: "user",
              content: `Email content: ${content}`,
            },
          ],
          max_tokens: 4096,
          stream: false,
        }),
      }
    ).then((r) => r.json());

    return markdown(
      res.choices[0].message.content.split("</think>")[1]
    ).toString();
  } catch (e) {
    return content;
  }
};

export const OPTIONS = async () => {
  return new Response("", {
    status: 200,
    headers: { "Access-Control-Allow-Headers": "*" },
  });
};
// const footer = `\n\n Don't reply to this email - it's autogenerated. If you have any questions, please reach out to hello@dysperse.com`;

export async function POST(req: NextRequest) {
  try {
    const params = await getApiParams(
      req,
      [
        { name: "from", required: true },
        { name: "subject", required: true },
        { name: "body", required: true },
      ],
      { type: "BODY" }
    );

    const user = await prisma.user.findFirst({
      where: { email: params.from },
      select: {
        id: true,
        spaces: {
          where: { selected: true },
          select: { spaceId: true },
          take: 1,
        },
        timeZone: true,
        profile: { select: { name: true } },
      },
    });

    if (!user) {
      return Response.json({
        success: false,
        subject: "😔 Oh no! We couldn't find your account.",
        body: render(
          ForwardedEmail({
            error: "We couldn't find your account.",
            toEmail: params.from,
          })
        ),
      });
    }

    const note = await getDescription(params.body);

    const data = await prisma.entity.create({
      data: {
        type: "TASK",
        name: params.subject,
        integrationParams: {
          type: "EMAIL_FORWARD",
          from: params.from,
          icon: "mail",
        },
        pinned:
          [
            "urgent",
            "important",
            "asap",
            "as soon as possible",
            "soon",
            "quick",
            "critical",
            "required",
            "action",
            "⚠️",
            "🚨",
          ].map((t) => params.subject.toLowerCase().includes(t)).length > 0,
        note,
        hasSimplifiedNote: note !== params.body,
        shortId: generateRandomString(6),
        start: dayjs()
          .startOf("day")
          .utc()
          .tz(user.timeZone || "UTC")
          .toDate(),
        published: true,
        space: { connect: { id: user.spaces[0].spaceId } },
      },
    });

    if (process.env.NODE_ENV === "production")
      new Notification("EMAIL_FORWARDING", {
        title: "🎉 We recieved your email!",
        body: "We've added a task to your to-do list!",
      }).dispatch(user.id);

    return Response.json({
      success: true,
      subject: "🎉 #dysperse added your email as a task!",
      body: render(
        ForwardedEmail({
          toEmail: params.from,
          toName: (user.profile as any).name,
          shortId: (data as any).shortId,
          taskData: data,
        })
      ),
    });
  } catch (e) {
    return handleApiError(e);
  }
}

