import { getApiParams } from "@/lib/getApiParams";
import { handleApiError } from "@/lib/handleApiError";
import { prisma } from "@/lib/prisma";
import { generateRandomString } from "@/lib/randomString";
import { NextRequest } from "next/server";
export const dynamic = "force-dynamic";

export const OPTIONS = async () => {
  return new Response("", {
    status: 200,
    headers: { "Access-Control-Allow-Headers": "*" },
  });
};
export async function POST(req: NextRequest) {
  try {
    const params = await getApiParams(
      req,
      [
        { name: "from", required: true },
        { name: "subject", required: true },
        { name: "description", required: true },
      ],
      { type: "BODY" }
    );

    const user = await prisma.user.findFirst({
      where: { email: params.from },
      select: { spaces: { where: { selected: true } } },
    });
    if (!user) {
      return Response.json({
        success: false,
        subject: "😔 Oh no! We couldn't find your account.",
        body: "We got your email, but we couldn't find a Dysperse account associated with it. Try resending your email using the email address associated with your Dysperse account.",
      });
    }

    const data = await prisma.entity.create({
      data: {
        type: "TASK",
        name: params.subject,
        note: params.description,
        shortId: generateRandomString(6),
        published: true,
        space: { connect: { id: user.spaces[0].id } },
      },
    });
    return Response.json({
      success: true,
      subject: "🎉 #dysperse added your email as a task!",
      body: `We've added your task to Dysperse. You can view it here: https://dys.us.to/${data.shortId}\n\n Don't reply to this email - it's autogenerated. If you have any questions, please reach out to hello@dysperse.com`,
    });
  } catch (e) {
    return handleApiError(e);
  }
}
