export const categories = [
  "Education",
  "Health",
  "Career",
  "Finance",
  "Relationships",
  "Hobbies",
  "Travel",
  "Personal Growth",
  "Mental health",
];

export const goals = [
  {
    name: "100 days of code",
    stepName: "Code for 1 hour",
    category: "Education",
    description: "Code for 1 hour every day, for 100 days",
    durationDays: 100,
    time: "any",
    icon: "auto_awesome",
  },
  {
    name: "3 minutes of meditation",
    stepName: "Meditate for 3 minutes",
    category: "Mental health",
    description: "Meditate for 3 minutes every day, for 10 days",
    durationDays: 10,
    time: "any",
    icon: "auto_awesome",
  },
  {
    name: "10 pushups every morning",
    stepName: "Do 10 pushups",
    category: "Health",
    description: "Do 10 pushups every morning, for 30 days",
    durationDays: 30,
    time: "morning",
    icon: "auto_awesome",
  },
  {
    name: "Read 1 chapter of a book",
    stepName: "Read a chapter",
    category: "Education",
    description: "Read 1 chapter of a book every day, for 30 days",
    durationDays: 30,
    time: "night",
    icon: "auto_awesome",
  },
  {
    name: "Drink 2 liters of water",
    stepName: "Drink 2 liters of water",
    category: "Health",
    description: "Drink 2 liters of water every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Go for a walk",
    stepName: "Go for a walk",
    category: "Health",
    description: "Go for a walk every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Go to the gym",
    stepName: "Go to the gym",
    category: "Health",
    description: "Go to the gym every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Write a blog post",
    stepName: "Write a blog post",
    category: "Career",
    description: "Write a blog post every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Take a class",
    stepName: "Take a class",
    category: "Education",
    description: "Take a class every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Write an email to a friend",
    stepName: "Write an email to a friend",
    category: "Relationships",
    description: "Write an email to a friend every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Call a friend",
    stepName: "Call a friend",
    category: "Relationships",
    description: "Call a friend every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
  {
    name: "Cook a new recipe",
    stepName: "Cook a new recipe",
    category: "Health",
    description: "Cook a new recipe every day, for 7 days",
    durationDays: 7,
    time: "any",
    icon: "",
  },
  {
    name: "Learn a new language",
    stepName: "Learn a new language",
    category: "Education",
    description: "Learn a new language every day, for 100 days",
    durationDays: 100,
    time: "any",
    icon: "",
  },
  {
    name: "Learn a new skill",
    stepName: "Learn a new skill",
    category: "Education",
    description: "Learn a new skill every day, for 7 days",
    durationDays: 7,
    time: "any",
    icon: "",
  },
  {
    name: "Write a book",
    stepName: "Write a book",
    category: "Education",
    description: "Write a book every day, for a year",
    durationDays: 365,
    time: "any",
    icon: "",
  },
  {
    name: "Write a poem",
    stepName: "Write a poem",
    category: "Education",
    description: "Write a poem every day, for 100 days",
    durationDays: 100,
    time: "any",
    icon: "",
  },
  {
    name: "Learn to play an instrument",
    stepName: "Learn to play an instrument",
    category: "Hobbies",
    description: "Learn to play an instrument every day, for 100 days",
    durationDays: 100,
    time: "any",
    icon: "",
  },
  {
    name: "Learn to dance",
    stepName: "Learn to dance",
    category: "Hobbies",
    description: "Learn to dance every day, for 10 days",
    durationDays: 10,
    time: "any",
    icon: "",
  },
  {
    name: "Visit a place",
    stepName: "Visit a place",
    category: "Hobbies",
    description: "Visit a place every day, for 7 days",
    durationDays: 7,
    time: "any",
    icon: "",
  },
  {
    name: "Limit your screen time to 1.5 hours",
    stepName: "Limit your screen time to 1.5 hours",
    category: "Mental health",
    description: "Limit your screen time to 1.5 hours every day, for 30 days",
    durationDays: 30,
    time: "any",
    icon: "",
  },
];
