name: coach-cron
on:
  schedule:
    - cron: "0 6 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: cron-runner
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://my.dysperse.com/api/coach-notif' \
          --header 'Authorization: Bearer ${{ secrets.COACH_CRON_API_KEY }}'
