name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Send message
      uses: Smartlist-App/discord-webhook@v4.0.0
      with:
        webhook-url: ${{ secrets.WEBHOOK_URL }}
        raw-data: message.json