name: discord message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: Smartlist-App/checkout@master
      - name: send message
        uses: Smartlist-App/discord-action@master
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#DB94CA"
          username: "GitHub [BOT]"
          message: "A new version of Dysperse is available! \nChanges: ${{ github.event.commits[0].message }} \nVisit https://api.dysperse.com to view the latest deployment"
