name: discord message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: Smartlist-App/checkout@master
    - name: Send message
      uses: Smartlist-App/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        color: "#06b6d4"
        username: "GitHub"
        message: "A new version of Smartlist is available! \n Change description: ${{github.event.head_commit.message}} \n Visit https://lab-1.smartlist.tech to view the latest deployment"